# 此配置将会所有项目公用

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.11.11.73:10010/eureka/,http://10.11.11.74:10010/eureka/
        
spring:
  rabbitmq:
    host: 10.11.13.99
    port: 10199
    username: admin
    password: QkMqProd^78
    virtualHost: /
    publisherConfirms: true
  redis:
    database: 1 # Redis数据库索引（默认为0,有0-15共16个数据库）
    timeout: 15000
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
    cluster:
      nodes:
      - redis01-01.szqk-tech.com:6379
      - redis01-02.szqk-tech.com:6379
      - redis01-03.szqk-tech.com:6379
      - redis01-04.szqk-tech.com:6379
      - redis01-05.szqk-tech.com:6379
      - redis01-06.szqk-tech.com:6379
    password: QKrdS$201801
  redisson:
    iscluster: true
    scanInterval: 1000
    failedAttempts: 3
    reconnectionTimeout: 3000
    retryInterval: 1500
    retryAttempts: 3
    timeout: 3000
    connectTimeout: 10000
    idleConnectionTimeout: 10000
    masterConnectionPoolSize: 64
    slaveConnectionMinimumIdleSize: 10


# fast配置
fastdfs:
  http:
    url: http://10.10.11.136
  service:
    ip: http://10.10.11.136
    id: 10001
  update:
    url: http://10.10.11.136/fdfs-client/upload/file?service_id=10001&sign=SIGN
  md5:
    key: 1fc999b7a5e94a25be4fe42df6fc80f4
